=== giellalt/dict-sma-mul/dtd/smamul.dtd
<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
    xml:lang ( sma ) #IMPLIED
>
<!ATTLIST r
      id ( smamul ) #IMPLIED >


<!-- the header -->
<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'
    xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>

<!ELEMENT e (lg, source?, semantics?, stem*, sources?, mg+, ig*) >
<!ATTLIST e
      usage ( mt | vd | dict | other | nds | fad | KB ) #IMPLIED
      src ( nj | sk | SvSt | gt_fad | gt | fad | other | gg | SK |
            PS_SA | KAL | nou94 | PS | husbykuhmunen | lmm | sammallahti |
            BergslandMagga | Lagercrantz | nsr | utsi | aj )  #IMPLIED
      exclude ( smanob | nobsma ) #IMPLIED
      reverse ( yes | no ) #IMPLIED
      illpl ( yes | no ) #IMPLIED
      id CDATA #IMPLIED
      xpos CDATA #IMPLIED
      mc CDATA #IMPLIED
>
<!ATTLIST e r ( LR | RL ) #IMPLIED > <!-- found in all_smnsme.xml -->
<!ATTLIST e note CDATA #IMPLIED >
<!ATTLIST e oa_unif ( done | s | N | E ) #IMPLIED >

<!ELEMENT lg (l+, l_ref*, lemma_ref*, lsub*, stem*, analysis*, mini_paradigm*) >
<!ELEMENT lemma_ref (#PCDATA) >
<!ELEMENT orig (#PCDATA) >

<!ATTLIST lemma_ref lemmaID CDATA #IMPLIED >
<!ATTLIST lg freq CDATA #IMPLIED >

<!ELEMENT analysis (#PCDATA|wordform)* >
<!ATTLIST analysis ms CDATA #IMPLIED >

<!ELEMENT wordform (#PCDATA) >
<!ELEMENT mini_paradigm (analysis+) >

<!ELEMENT l (#PCDATA) >
<!ATTLIST l
      attr CDATA #IMPLIED
      case CDATA #IMPLIED 
      class ( I | II | III | IV | V | VI | xxx ) #IMPLIED
      context CDATA #IMPLIED
      dialect CDATA #IMPLIED
      diph ( yes ) #IMPLIED
      hid CDATA #IMPLIED 
      illpl ( ok | no ) #IMPLIED
      margo CDATA #IMPLIED
      minip ( notSg1 | onlyPl ) #IMPLIED
      mod CDATA #IMPLIED 
      nr ( Sg | Du | Pl ) #IMPLIED
      p3p CDATA #IMPLIED
      pg ( yes | no ) #IMPLIED
      pos ( A | Adv | CC | CS  | Interj | N | Num |
            Pcle | Phrase | Po | Pr | Pron | V ) #IMPLIED 
      sem_type ( Obj | Plc | Fem | Org | Mal | Txt ) #IMPLIED 
      soggi CDATA #IMPLIED
      src CDATA #IMPLIED 
      stem ( even | odd | 2syll | 3syll | xsyll | weak ) #IMPLIED
      type ( Rel | Pers | Indef | Refl | Dem | interr |
             pre | post | ord | TV | IV | actor | G3 | G7 | NomAg | Ord
             | Prop | Recipr | Coll | Interr | Logo ) #IMPLIED
      umlaut ( full | A | C | B | D | E | F ) #IMPLIED
      vow CDATA #IMPLIED
>

<!-- decl: i indeclineable -->

<!-- lsub = frequent subform of lemma -->
<!ELEMENT lsub (#PCDATA) >

<!ELEMENT lc (#PCDATA) >

<!-- algu = lemma IDs in the algu database -->
<!ELEMENT algu EMPTY >
<!ATTLIST algu
      lekseemi_id CDATA #REQUIRED >
<!ATTLIST algu
      sanue_id CDATA #REQUIRED >


<!-- the real stem field -->
<!ELEMENT stem (#PCDATA) >
<!ATTLIST stem class ( bisyllabic | trisyllabic ) #IMPLIED >

<!-- the mg -->
<!ELEMENT mg (l_ref?, dg?, tg+, ig? ) >

<!-- Idiom phrases, faste uttrykk -->
<!ELEMENT ig ( i+, id?, it+)+ >
<!ELEMENT i (#PCDATA) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT it (#PCDATA) >


<!ELEMENT dg ( d ) >
<!ELEMENT d (#PCDATA) >

<!ELEMENT tg (semantics?, re?,  ( ((t, stem*, l_ref?, morph_expl?)))+, xg*) >
<!ATTLIST tg
      xml:lang ( nob | swe | sme | lat | eng ) #REQUIRED
      check CDATA #IMPLIED
>
<!ELEMENT re (#PCDATA) > <!-- Domain restriction: bot, phys, ... -->
<!ATTLIST re
    xml:lang ( nob | sme | sma | smn | swe | eng | deu | lat) #IMPLIED
>

<!ELEMENT t (#PCDATA) >
<!ATTLIST t t_type ( Pers | expl ) #IMPLIED  >
<!ATTLIST t pos ( A | Adv | CC | CS | Det | Interj | N | Num |
                  Phrase | Po | Pr | Pron | V ) #IMPLIED >

<!ATTLIST t type ( expl
                  | grammarexpl |Prop | Indef | G3 | NomAg | Coll | Recipr | Pers
                  | grammar | Refl | Dem | Poss | Logo | Rel | Interr | TV | IV ) #IMPLIED >
<!ATTLIST t src CDATA #IMPLIED >
<!ATTLIST t orig CDATA #IMPLIED >
<!ATTLIST t href CDATA #IMPLIED >
<!ATTLIST t value CDATA #IMPLIED >
<!ATTLIST t soggi CDATA #IMPLIED >

<!ELEMENT l_ref (#PCDATA) >

<!-- translation_comment = for Oahpa use -->


<!ELEMENT morph_expl (#PCDATA) >


<!ELEMENT xg ((x, xt+)+)>
<!ATTLIST xg re CDATA #IMPLIED >
<!ELEMENT x (#PCDATA)>
<!ATTLIST x src CDATA #IMPLIED >
<!ELEMENT xt (#PCDATA)>
<!ATTLIST xt src CDATA #IMPLIED >


<!ELEMENT xhtml:script EMPTY >
<!ATTLIST xhtml:script type CDATA #FIXED "text/javascript" >
<!ATTLIST xhtml:script src  CDATA #IMPLIED >
<!ATTLIST xhtml:script xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml" >

=== giellalt/dict-sma-mul/src/cc_smamul.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../smamul.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="smamul" xml:lang="sma">
   <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve"><lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic><ref>Work by Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref><sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:feedback@divvun.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote></lics>
   <e usage="dict">
      <lg>
         <l pos="CC">gon</l>
      </lg>
      <mg>
         <l_ref>jïh_cc</l_ref>
         <tg xml:lang="nob">
            <re>om to som hører sammen</re>
            <t pos="CC">og</t>
            <xg>
               <x>Manne aadtjegh aahka gon aajjan luvnie vearadamme.</x>
               <xt>Jeg har nettopp vært hos bestemor og bestefar.</xt>
            </xg>
         </tg>
         <tg xml:lang="swe">
            <t pos="CC">och</t>
         </tg>
      </mg>
   </e>
   <e usage="dict">
      <lg>
         <l pos="CC">gonnoeh</l>
      </lg>
      <mg>
         <l_ref>jïh_cc</l_ref>
         <tg xml:lang="nob">
            <re>om to som hører sammen</re>
            <t pos="CC">og</t>
            <xg>
               <x>tjidtjie gonnoeh aehtjieh</x>
               <xt>mor og far</xt>
            </xg>
         </tg>
         <tg xml:lang="swe">
            <t pos="CC">och</t>
         </tg>
      </mg>
   </e>
   <e usage="dict">
      <lg>
         <l pos="CC">jallh</l>
      </lg>
      <mg>
         <l_ref>vuj_cc</l_ref>
         <tg xml:lang="nob">
            <t pos="CC">eller</t>
            <xg>
              <x>Gogkoe ij leah geajnoe, dagkoe hov maahta girtine jallh helikopterinie fealadidh.</x>
              <xt>Der det ikke er vei kan man reise med fly eller helikopter.</xt>
            </xg>
         </tg>
         <tg xml:lang="swe">
            <t pos="CC">eller</t>
         </tg>
      </mg>
   </e>
   <e usage="dict">
      <lg>
         <l pos="CC">jïh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">og</t>
            <xg>
               <x>Dovne Pöövle jïh Laara ligan desnie.</x>
               <xt>Både Paul og Lars var der.</xt>
            </xg>
         </tg>
         <tg xml:lang="swe">
            <t pos="CC">og_SWE</t>
         </tg>
      </mg>
   </e>
   <e usage="dict">
      <lg>
         <l pos="CC">men</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">men</t>
         </tg>
         <tg xml:lang="swe">
            <t pos="CC">men_SWE</t>
         </tg>
      </mg>
   </e>
   <e usage="dict">
      <lg>
         <l pos="CC">mohte</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">men</t>
            <xg>
               <x>Sliehtie-elmie, mohte tjaktje hov lea.</x>
               <xt>Det er ruskevær med sludd, men så er det jo høst.</xt>
            </xg>
            <xg>
               <x>Dïhte geajnoe dahkoe lea dan siegkie, mohte dïhte mubpie geajnoe sagki buerebe.</x>
               <xt>Den veien dit er så smal, men den andre veien er mye bedre.</xt>
            </xg>
         </tg>
         <tg xml:lang="swe">
            <t pos="CC">men_SWE</t>
         </tg>
      </mg>
   </e>
   <e usage="dict">
      <lg>
         <l pos="CC">vïj</l>
      </lg>
      <mg>
         <l_ref>jallh_cc</l_ref>
         <tg xml:lang="nob">
            <re>i spørsmål om to alternativer</re>
            <t pos="CC">eller</t>
         </tg>
         <tg xml:lang="swe">
            <re>i spørsmål om to_SWE</re>
            <t pos="CC">eller_SWE</t>
         </tg>
      </mg>
   </e>
   <e usage="dict">
      <lg>
         <l pos="CC">vuj</l>
      </lg>
      <mg>
         <l_ref>jallh_cc</l_ref>
         <tg xml:lang="nob">
            <re>i spørsmål om to alternativer</re>
            <t pos="CC">eller</t>
            <xg>
               <x>Mejtie tseagkoeh gåetie vuj slapmoeh gåetie?</x>
               <xt>Er det en opprettstående kåte eller en lav og vid kåte?</xt>
            </xg>
         </tg>
         <tg xml:lang="swe">
            <re>i spørsmål om to_SWE</re>
            <t pos="CC">eller_SWE</t>
         </tg>
      </mg>
   </e>
   <xhtml:script xmlns:xhtml="http://www.w3.org/1999/xhtml" src="../../giella-core/dicts/scripts/gt_dictionary.js" type="text/javascript"/>
</r>

=== giellalt/dict-sma-mul/src/propPl_smamul.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!--
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/smamul.dtd">
-->
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/smamul.dtd">

<r id="smamul" xml:lang="sma">
   <lics xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:feedback@divvun.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Njuanajaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Rindal</re>
            <t pos="N" type="Prop">Tangvatna</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Tjohkeleh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Selbu</re>
            <t pos="N" type="Prop">Skarvan</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Faatnajabpejaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Tydal</re>
            <t pos="N" type="Prop">Skreddarsjøane</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Bealjehkh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Tydal</re>
            <t pos="N" type="Prop">Sylan</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Pliehkiejaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Meråker</re>
            <t pos="N" type="Prop">Lødøljsjøan</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Saedtietjaerhvieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Nordli</re>
            <t pos="N" type="Prop">Grønflatknulen</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Aahkabieljieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Nordli</re>
            <t pos="N" type="Prop">Akkavassøran</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Guelehtsjaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Nordli</re>
            <t pos="N" type="Prop">Fiskløysvatna</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Golmesjaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Røyrvik</re>
            <t pos="N" type="Prop">Storgollomsvatnet</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Gåetbielesdurrienjaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Røyrvik</re>
            <t pos="N" type="Prop">Husviktjønnin</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Tjaeksienjaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Røyrvik</re>
            <t pos="N" type="Prop">Renselskardtjønnin</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Måarenjaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Røyrvik</re>
            <t pos="N" type="Prop">Beinvatna</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Tjiermejaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Røyrvik</re>
            <t pos="N" type="Prop">Tjermavatna</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Jassehkentjonneh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Røyrvik</re>
            <t pos="N" type="Prop">Jassånilstjønnin</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Sieteretjonneh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Namsskogan</re>
            <t pos="N" type="Prop">Sætertjørnin</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Guhkiestjonneh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Namsskogan</re>
            <t pos="N" type="Prop">Langtjønna</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Jahtedh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Høylandet</re>
            <t pos="N" type="Prop">Finntroppin</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Snuvrejaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Høylandet</re>
            <t pos="N" type="Prop">Årkverntjørnin</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Gaelpientjonneh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Nordbindalen</re>
            <t pos="N" type="Prop">Nilsinetjørnin</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Gaelpienjaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Nordbindalen</re>
            <t pos="N" type="Prop">Nilsinetjørnin</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Grovhtemehkienjaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Nordbindalen</re>
            <t pos="N" type="Prop">Grytendalsvatnan</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Bueleksjællanjaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Nordbindalen</re>
            <t pos="N" type="Prop">Nilsfinntjønnin</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Giedtiejaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Hattfjelldal</re>
            <t pos="N" type="Prop">Sætertjønnan</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Pingkelejaavretjh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Hattfjelldal</re>
            <t pos="N" type="Prop">Pinkelvatnan</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Gaajsetjenjaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Mo</re>
            <t pos="N" type="Prop">Jordbekkvatnan</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Plierehkejaevrieh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Mo</re>
            <t pos="N" type="Prop">Blerekvatnan</t>
         </tg>
      </mg>
   </e>
   <e src="sk" usage="dict">
      <lg>
         <l pos="N" type="Prop" nr="Pl" sem_type="Plc">Gaajsetjh</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>Mo</re>
            <t pos="N" type="Prop">Småtindan</t>
         </tg>
      </mg>
   </e>
   <xhtml:script xmlns:xhtml="http://www.w3.org/1999/xhtml" src="../../giella-core/dicts/scripts/gt_dictionary.js" type="text/javascript"/>
</r>
